- hosts: localhost
  tasks:
    - name: brew update
      shell: brew update
    - name: brew upgrade
      shell: brew upgrade
    - name: gem install rubygems-update
      shell: gem install rubygems-update
    - name: gem update --system
      shell: gem update --system
    - name: brew cleanup
      shell: brew cleanup
    - name: gem cleanup
      shell: gem cleanup
    - name: pyenv rehash
      shell: pyenv rehash
    - name: pip install --upgrade pip
      shell: pip install --upgrade pip
